export const KEY = "2e86f4a1fb6e43a4a42180220231010";
export const DEFAULT_CITY = "Kyiv";
export const FLAGS = [
  { name: "ascension island", emoji: "🇦🇨" },
  { name: "andorra", emoji: "🇦🇩" },
  { name: "united arab emirates", emoji: "🇦🇪" },
  { name: "afghanistan", emoji: "🇦🇫" },
  { name: "antigua and barbuda", emoji: "🇦🇬" },
  { name: "anguilla", emoji: "🇦🇮" },
  { name: "albania", emoji: "🇦🇱" },
  { name: "armenia", emoji: "🇦🇲" },
  { name: "angola", emoji: "🇦🇴" },
  { name: "antarctica", emoji: "🇦🇶" },
  { name: "argentina", emoji: "🇦🇷" },
  { name: "american samoa", emoji: "🇦🇸" },
  { name: "austria", emoji: "🇦🇹" },
  { name: "australia", emoji: "🇦🇺" },
  { name: "aruba", emoji: "🇦🇼" },
  { name: "åland islands", emoji: "🇦🇽" },
  { name: "azerbaijan", emoji: "🇦🇿" },
  { name: "bosnia and herzegovina", emoji: "🇧🇦" },
  { name: "barbados", emoji: "🇧🇧" },
  { name: "bangladesh", emoji: "🇧🇩" },
  { name: "belgium", emoji: "🇧🇪" },
  { name: "burkina faso", emoji: "🇧🇫" },
  { name: "bulgaria", emoji: "🇧🇬" },
  { name: "bahrain", emoji: "🇧🇭" },
  { name: "burundi", emoji: "🇧🇮" },
  { name: "benin", emoji: "🇧🇯" },
  { name: "st. barthélemy", emoji: "🇧🇱" },
  { name: "bermuda", emoji: "🇧🇲" },
  { name: "brunei", emoji: "🇧🇳" },
  { name: "bolivia", emoji: "🇧🇴" },
  { name: "caribbean netherlands", emoji: "🇧🇶" },
  { name: "brazil", emoji: "🇧🇷" },
  { name: "bahamas", emoji: "🇧🇸" },
  { name: "bhutan", emoji: "🇧🇹" },
  { name: "bouvet island", emoji: "🇧🇻" },
  { name: "botswana", emoji: "🇧🇼" },
  { name: "belarus", emoji: "🇧🇾" },
  { name: "belize", emoji: "🇧🇿" },
  { name: "canada", emoji: "🇨🇦" },
  { name: "cocos (keeling) islands", emoji: "🇨🇨" },
  { name: "congo - kinshasa", emoji: "🇨🇩" },
  { name: "central african republic", emoji: "🇨🇫" },
  { name: "congo - brazzaville", emoji: "🇨🇬" },
  { name: "switzerland", emoji: "🇨🇭" },
  { name: "côte d’ivoire", emoji: "🇨🇮" },
  { name: "cook islands", emoji: "🇨🇰" },
  { name: "chile", emoji: "🇨🇱" },
  { name: "cameroon", emoji: "🇨🇲" },
  { name: "china", emoji: "🇨🇳" },
  { name: "colombia", emoji: "🇨🇴" },
  { name: "clipperton island", emoji: "🇨🇵" },
  { name: "costa rica", emoji: "🇨🇷" },
  { name: "cuba", emoji: "🇨🇺" },
  { name: "cape verde", emoji: "🇨🇻" },
  { name: "curaçao", emoji: "🇨🇼" },
  { name: "christmas island", emoji: "🇨🇽" },
  { name: "cyprus", emoji: "🇨🇾" },
  { name: "czechia", emoji: "🇨🇿" },
  { name: "germany", emoji: "🇩🇪" },
  { name: "diego garcia", emoji: "🇩🇬" },
  { name: "djibouti", emoji: "🇩🇯" },
  { name: "denmark", emoji: "🇩🇰" },
  { name: "dominica", emoji: "🇩🇲" },
  { name: "dominican republic", emoji: "🇩🇴" },
  { name: "algeria", emoji: "🇩🇿" },
  { name: "ceuta and melilla", emoji: "🇪🇦" },
  { name: "ecuador", emoji: "🇪🇨" },
  { name: "estonia", emoji: "🇪🇪" },
  { name: "egypt", emoji: "🇪🇬" },
  { name: "western sahara", emoji: "🇪🇭" },
  { name: "eritrea", emoji: "🇪🇷" },
  { name: "spain", emoji: "🇪🇸" },
  { name: "ethiopia", emoji: "🇪🇹" },
  { name: "european union", emoji: "🇪🇺" },
  { name: "finland", emoji: "🇫🇮" },
  { name: "fiji", emoji: "🇫🇯" },
  { name: "falkland islands", emoji: "🇫🇰" },
  { name: "micronesia", emoji: "🇫🇲" },
  { name: "faroe islands", emoji: "🇫🇴" },
  { name: "france", emoji: "🇫🇷" },
  { name: "gabon", emoji: "🇬🇦" },
  { name: "united kingdom", emoji: "🇬🇧" },
  { name: "grenada", emoji: "🇬🇩" },
  { name: "georgia", emoji: "🇬🇪" },
  { name: "french guiana", emoji: "🇬🇫" },
  { name: "guernsey", emoji: "🇬🇬" },
  { name: "ghana", emoji: "🇬🇭" },
  { name: "gibraltar", emoji: "🇬🇮" },
  { name: "greenland", emoji: "🇬🇱" },
  { name: "gambia", emoji: "🇬🇲" },
  { name: "guinea", emoji: "🇬🇳" },
  { name: "guadeloupe", emoji: "🇬🇵" },
  { name: "equatorial guinea", emoji: "🇬🇶" },
  { name: "greece", emoji: "🇬🇷" },
  { name: "south georgia and south sandwich islands", emoji: "🇬🇸" },
  { name: "guatemala", emoji: "🇬🇹" },
  { name: "guam", emoji: "🇬🇺" },
  { name: "guinea-bissau", emoji: "🇬🇼" },
  { name: "guyana", emoji: "🇬🇾" },
  { name: "hong kong sar china", emoji: "🇭🇰" },
  { name: "heard and mcdonald islands", emoji: "🇭🇲" },
  { name: "honduras", emoji: "🇭🇳" },
  { name: "croatia", emoji: "🇭🇷" },
  { name: "haiti", emoji: "🇭🇹" },
  { name: "hungary", emoji: "🇭🇺" },
  { name: "canary islands", emoji: "🇮🇨" },
  { name: "indonesia", emoji: "🇮🇩" },
  { name: "ireland", emoji: "🇮🇪" },
  { name: "israel", emoji: "🇮🇱" },
  { name: "isle of man", emoji: "🇮🇲" },
  { name: "india", emoji: "🇮🇳" },
  { name: "british indian ocean territory", emoji: "🇮🇴" },
  { name: "iraq", emoji: "🇮🇶" },
  { name: "iran", emoji: "🇮🇷" },
  { name: "iceland", emoji: "🇮🇸" },
  { name: "italy", emoji: "🇮🇹" },
  { name: "jersey", emoji: "🇯🇪" },
  { name: "jamaica", emoji: "🇯🇲" },
  { name: "jordan", emoji: "🇯🇴" },
  { name: "japan", emoji: "🇯🇵" },
  { name: "kenya", emoji: "🇰🇪" },
  { name: "kyrgyzstan", emoji: "🇰🇬" },
  { name: "cambodia", emoji: "🇰🇭" },
  { name: "kiribati", emoji: "🇰🇮" },
  { name: "comoros", emoji: "🇰🇲" },
  { name: "st. kitts and nevis", emoji: "🇰🇳" },
  { name: "north korea", emoji: "🇰🇵" },
  { name: "south korea", emoji: "🇰🇷" },
  { name: "kuwait", emoji: "🇰🇼" },
  { name: "cayman islands", emoji: "🇰🇾" },
  { name: "kazakhstan", emoji: "🇰🇿" },
  { name: "laos", emoji: "🇱🇦" },
  { name: "lebanon", emoji: "🇱🇧" },
  { name: "st. lucia", emoji: "🇱🇨" },
  { name: "liechtenstein", emoji: "🇱🇮" },
  { name: "sri lanka", emoji: "🇱🇰" },
  { name: "liberia", emoji: "🇱🇷" },
  { name: "lesotho", emoji: "🇱🇸" },
  { name: "lithuania", emoji: "🇱🇹" },
  { name: "luxembourg", emoji: "🇱🇺" },
  { name: "latvia", emoji: "🇱🇻" },
  { name: "libya", emoji: "🇱🇾" },
  { name: "morocco", emoji: "🇲🇦" },
  { name: "monaco", emoji: "🇲🇨" },
  { name: "moldova", emoji: "🇲🇩" },
  { name: "montenegro", emoji: "🇲🇪" },
  { name: "st. martin", emoji: "🇲🇫" },
  { name: "madagascar", emoji: "🇲🇬" },
  { name: "marshall islands", emoji: "🇲🇭" },
  { name: "north macedonia", emoji: "🇲🇰" },
  { name: "mali", emoji: "🇲🇱" },
  { name: "myanmar (burma)", emoji: "🇲🇲" },
  { name: "mongolia", emoji: "🇲🇳" },
  { name: "macao sar china", emoji: "🇲🇴" },
  { name: "northern mariana islands", emoji: "🇲🇵" },
  { name: "martinique", emoji: "🇲🇶" },
  { name: "mauritania", emoji: "🇲🇷" },
  { name: "montserrat", emoji: "🇲🇸" },
  { name: "malta", emoji: "🇲🇹" },
  { name: "mauritius", emoji: "🇲🇺" },
  { name: "maldives", emoji: "🇲🇻" },
  { name: "malawi", emoji: "🇲🇼" },
  { name: "mexico", emoji: "🇲🇽" },
  { name: "malaysia", emoji: "🇲🇾" },
  { name: "mozambique", emoji: "🇲🇿" },
  { name: "namibia", emoji: "🇳🇦" },
  { name: "new caledonia", emoji: "🇳🇨" },
  { name: "niger", emoji: "🇳🇪" },
  { name: "norfolk island", emoji: "🇳🇫" },
  { name: "nigeria", emoji: "🇳🇬" },
  { name: "nicaragua", emoji: "🇳🇮" },
  { name: "netherlands", emoji: "🇳🇱" },
  { name: "norway", emoji: "🇳🇴" },
  { name: "nepal", emoji: "🇳🇵" },
  { name: "nauru", emoji: "🇳🇷" },
  { name: "niue", emoji: "🇳🇺" },
  { name: "new zealand", emoji: "🇳🇿" },
  { name: "oman", emoji: "🇴🇲" },
  { name: "panama", emoji: "🇵🇦" },
  { name: "peru", emoji: "🇵🇪" },
  { name: "french polynesia", emoji: "🇵🇫" },
  { name: "papua new guinea", emoji: "🇵🇬" },
  { name: "philippines", emoji: "🇵🇭" },
  { name: "pakistan", emoji: "🇵🇰" },
  { name: "poland", emoji: "🇵🇱" },
  { name: "st. pierre & miquelon", emoji: "🇵🇲" },
  { name: "pitcairn islands", emoji: "🇵🇳" },
  { name: "puerto rico", emoji: "🇵🇷" },
  { name: "palestinian territories", emoji: "🇵🇸" },
  { name: "portugal", emoji: "🇵🇹" },
  { name: "palau", emoji: "🇵🇼" },
  { name: "paraguay", emoji: "🇵🇾" },
  { name: "qatar", emoji: "🇶🇦" },
  { name: "réunion", emoji: "🇷🇪" },
  { name: "romania", emoji: "🇷🇴" },
  { name: "serbia", emoji: "🇷🇸" },
  { name: "russia", emoji: "🇷🇺" },
  { name: "rwanda", emoji: "🇷🇼" },
  { name: "saudi arabia", emoji: "🇸🇦" },
  { name: "solomon islands", emoji: "🇸🇧" },
  { name: "seychelles", emoji: "🇸🇨" },
  { name: "sudan", emoji: "🇸🇩" },
  { name: "sweden", emoji: "🇸🇪" },
  { name: "singapore", emoji: "🇸🇬" },
  { name: "st. helena", emoji: "🇸🇭" },
  { name: "slovenia", emoji: "🇸🇮" },
  { name: "svalbard & jan mayen", emoji: "🇸🇯" },
  { name: "slovakia", emoji: "🇸🇰" },
  { name: "sierra leone", emoji: "🇸🇱" },
  { name: "san marino", emoji: "🇸🇲" },
  { name: "senegal", emoji: "🇸🇳" },
  { name: "somalia", emoji: "🇸🇴" },
  { name: "suriname", emoji: "🇸🇷" },
  { name: "south sudan", emoji: "🇸🇸" },
  { name: "são tomé & príncipe", emoji: "🇸🇹" },
  { name: "el salvador", emoji: "🇸🇻" },
  { name: "sint maarten", emoji: "🇸🇽" },
  { name: "syria", emoji: "🇸🇾" },
  { name: "eswatini", emoji: "🇸🇿" },
  { name: "tristan da cunha", emoji: "🇹🇦" },
  { name: "turks and caicos islands", emoji: "🇹🇨" },
  { name: "chad", emoji: "🇹🇩" },
  { name: "french southern territories", emoji: "🇹🇫" },
  { name: "togo", emoji: "🇹🇬" },
  { name: "thailand", emoji: "🇹🇭" },
  { name: "tajikistan", emoji: "🇹🇯" },
  { name: "tokelau", emoji: "🇹🇰" },
  { name: "timor-leste", emoji: "🇹🇱" },
  { name: "turkmenistan", emoji: "🇹🇲" },
  { name: "tunisia", emoji: "🇹🇳" },
  { name: "tonga", emoji: "🇹🇴" },
  { name: "turkey", emoji: "🇹🇷" },
  { name: "trinidad & tobago", emoji: "🇹🇹" },
  { name: "tuvalu", emoji: "🇹🇻" },
  { name: "taiwan", emoji: "🇹🇼" },
  { name: "tanzania", emoji: "🇹🇿" },
  { name: "ukraine", emoji: "🇺🇦" },
  { name: "uganda", emoji: "🇺🇬" },
  { name: "u.s. outlying islands", emoji: "🇺🇲" },
  { name: "united nations", emoji: "🇺🇳" },
  { name: "united states of america", emoji: "🇺🇸" },
  { name: "uruguay", emoji: "🇺🇾" },
  { name: "uzbekistan", emoji: "🇺🇿" },
  { name: "vatican city", emoji: "🇻🇦" },
  { name: "st. vincent and grenadines", emoji: "🇻🇨" },
  { name: "venezuela", emoji: "🇻🇪" },
  { name: "british virgin islands", emoji: "🇻🇬" },
  { name: "u.s. virgin islands", emoji: "🇻🇮" },
  { name: "vietnam", emoji: "🇻🇳" },
  { name: "vanuatu", emoji: "🇻🇺" },
  { name: "wallis & futuna", emoji: "🇼🇫" },
  { name: "samoa", emoji: "🇼🇸" },
  { name: "kosovo", emoji: "🇽🇰" },
  { name: "yemen", emoji: "🇾🇪" },
  { name: "mayotte", emoji: "🇾🇹" },
  { name: "south africa", emoji: "🇿🇦" },
  { name: "zambia", emoji: "🇿🇲" },
  { name: "zimbabwe", emoji: "🇿🇼" },
  { name: "england", emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "scotland", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { name: "wales", emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
];
